server:
  port: 8088
dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: nacos://127.0.0.1:8848
  config-center:
    address: nacos://127.0.0.1:8848
  metadata-report:
    address: nacos://127.0.0.1:8848
nacos:
  config:
    server-addr: 127.0.0.1:8848
hello: 123456

